### ISSUE TITLE
Consistent versioning for answer sheet in relation to question sheet version

### ISSUE THREAD

**Issue by alxlo** [isaqb-org/examination-foundation#15] opened 2020-09-27 18:37 UTC
Answer sheet is 2020.1-EN-rev3 while questions are 2020.1-EN-rev5.

**Either (A) we increase the version of the answer sheet to always match the question sheet.**
PRO: easy to implement
CON: Might be confusing when only something in the questions was fixed.

**Or (B) we refer at the start of the answer sheet to the version of the question sheet**
PRO: Clear cut versioning
CON: Another indirection; possible failure point when we forget this after changing questions; We actually change something on the answer sheet, so one could argue that we would require a new version of the answer sheet anyway (yes, that one gets you coming and going).

**Or (C) we refer at the start/end of the question sheet to the applicable version of the answer sheet.**
PRO: Clear cut versioning
CON: Similar disadvantages to (B) but in the other dependency direction.

I slightly prefer (A) so we have the same version number for questions and answers as one unit. Confusion will be avoided by the changelog (see #9 ).

**Comment by ewolff** [comment] 2020-09-27 20:45
I am not really involved with foundation level - not sure why it was assigned to me. Sorry . Can you explain what I should do?

**Comment by alxlo** [comment] 2020-09-27 21:38
> I am not really involved with foundation level - not sure why it was assigned to me. Sorry . Can you explain what I should do?

Sorry, you where the wrong Mr. Wolff, This one goes to @programming-wolf

**Comment by gernotstarke** [comment] 2020-09-28 06:15
in all cases - it's manual work and somebody WILL FORGET to adjust version. "A" sounds best to me - but leaves room for errors...

Root cause: Answers in different document than questions.
Initial thoughts how that might be resolved: https://github.com/isaqb-org/examination-foundation/wiki

But: lot's of work with minimal positive impact.

Downside: GmbH cannot edit questions any longer (most likely they won't edit anyway)

**Comment by gernotstarke** [comment] 2020-11-10 17:41
updated answer sheet to rev6 - although no answer was changed.

**Comment by gernotstarke** [comment] 2021-01-20 11:10
questions and answers MUST have identical rev numbers... will hopefully be automated once better tools are in place

**Closed by gernotstarke** 2021-01-20 11:10 UTC
Labels: bug, enhancement
